include: package:lint/analysis_options_package.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
  exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart
    - lib/**.gr.dart
    - lib/**.config.dart